<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TV5SK76" failures="0" tests="3" name="com.test.ExceptionTimeoutTest" time="2.329" errors="2" timestamp="2023-10-29T14:54:38 IST" skipped="0">
  <testcase classname="com.test.ExceptionTimeoutTest" name="time" time="0.006"/>
  <testcase classname="com.test.ExceptionTimeoutTest" name="infinitlooptest" time="2.090">
    <error message="Method com.test.ExceptionTimeoutTest.infinitlooptest() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.ExceptionTimeoutTest.infinitlooptest() didn't finish within the time-out 2000
at java.base@17.0.4.1/java.io.FileOutputStream.writeBytes(Native Method)
at java.base@17.0.4.1/java.io.FileOutputStream.write(FileOutputStream.java:349)
at java.base@17.0.4.1/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
at java.base@17.0.4.1/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
at java.base@17.0.4.1/java.io.PrintStream.write(PrintStream.java:570)
at java.base@17.0.4.1/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
at java.base@17.0.4.1/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
at java.base@17.0.4.1/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)
at java.base@17.0.4.1/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)
at java.base@17.0.4.1/java.io.PrintStream.writeln(PrintStream.java:723)
at java.base@17.0.4.1/java.io.PrintStream.println(PrintStream.java:938)
at app//com.test.ExceptionTimeoutTest.infinitlooptest(ExceptionTimeoutTest.java:13)
at java.base@17.0.4.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.4.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.4.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.4.1/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.4.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- infinitlooptest -->
  <testcase classname="com.test.ExceptionTimeoutTest" name="time1" time="0.233">
    <error message="
Method ExceptionTimeoutTest.time1()[pri:0, instance:com.test.ExceptionTimeoutTest@4145bad8] should have thrown an exception of type class java.lang.NumberFormatException" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method ExceptionTimeoutTest.time1()[pri:0, instance:com.test.ExceptionTimeoutTest@4145bad8] should have thrown an exception of type class java.lang.NumberFormatException
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:860)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:718)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- time1 -->
</testsuite> <!-- com.test.ExceptionTimeoutTest -->
